name: perforvnm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/achievement.png
    - assets/background_thanking.png
    - assets/menu.png
    - assets/menu_music.mp3
    - assets/pedro_staring.png